"""add_chat_highlight_table

Revision ID: 32f028bd60e5
Revises: d84b20869f13
Create Date: 2020-05-14 19:06:43.896192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f028bd60e5'
down_revision = 'd84b20869f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_highlight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('videoid', sa.String(), nullable=False),
    sa.Column('highlight_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('videoid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_highlight')
    # ### end Alembic commands ###
