"""init_user_info

Revision ID: 365bfc24e9a4
Revises: 
Create Date: 2020-04-17 01:24:38.010399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365bfc24e9a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pw', sa.String(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
