"""Integrate predict&predict7

Revision ID: 447bf3021dba
Revises: e86b01d929e7
Create Date: 2020-06-02 12:33:27.077196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '447bf3021dba'
down_revision = 'e86b01d929e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_predict7')
    op.add_column('chat_predict', sa.Column('predict_json', sa.JSON(), nullable=False))
    op.drop_column('chat_predict', 'posneg_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_predict', sa.Column('posneg_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('chat_predict', 'predict_json')
    op.create_table('chat_predict7',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sentiment7_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chat_predict7_pkey'),
    sa.UniqueConstraint('url', name='chat_predict7_url_key')
    )
    # ### end Alembic commands ###
