"""add_image_url

Revision ID: 783715d88f44
Revises: eb6c51d5688b
Create Date: 2020-05-16 02:48:28.048277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783715d88f44'
down_revision = 'eb6c51d5688b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'image_url')
    # ### end Alembic commands ###
