"""login_expiry_add_UC

Revision ID: 9596285d57c7
Revises: 29756c89efa6
Create Date: 2020-05-04 01:52:42.960242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9596285d57c7'
down_revision = '29756c89efa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login_expiry', ['uuid', 'email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_expiry', type_='unique')
    # ### end Alembic commands ###
