"""change_array_to_json

Revision ID: d84b20869f13
Revises: 91b9baa85048
Create Date: 2020-05-13 18:20:02.562994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84b20869f13'
down_revision = '91b9baa85048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound_highlight', sa.Column('highlight_json', sa.JSON(), nullable=False))
    op.drop_column('sound_highlight', 'highlight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound_highlight', sa.Column('highlight', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('sound_highlight', 'highlight_json')
    # ### end Alembic commands ###
