"""add_sound_highlight_table

Revision ID: dc494cf49028
Revises: e7fad5c210d0
Create Date: 2020-05-12 15:52:08.547653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc494cf49028'
down_revision = 'e7fad5c210d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_highlight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('highlight', sa.ARRAY(sa.String(), dimensions=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sound_highlight')
    # ### end Alembic commands ###
