"""add_keyword_table

Revision ID: e7fad5c210d0
Revises: 45b17b866fcc
Create Date: 2020-05-12 13:59:54.622681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fad5c210d0'
down_revision = '45b17b866fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('videoid', sa.String(), nullable=False),
    sa.Column('keyword', sa.ARRAY(sa.String(), dimensions=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'videoid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_keyword')
    # ### end Alembic commands ###
