"""modify_column_name

Revision ID: e86b01d929e7
Revises: 783715d88f44
Create Date: 2020-05-18 13:53:07.577338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e86b01d929e7'
down_revision = '783715d88f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_predict7',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('sentiment7_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.add_column('chat_predict', sa.Column('posneg_json', sa.JSON(), nullable=False))
    op.drop_column('chat_predict', 'highlight_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_predict', sa.Column('highlight_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('chat_predict', 'posneg_json')
    op.drop_table('chat_predict7')
    # ### end Alembic commands ###
